dist: xenial
language: bash
services:
    - docker
script:
    - chmod +x ./share/testing/lib/run.sh
    - docker-compose run --rm bash ./share/testing/lib/run.sh ./share/testing
    - docker-compose run --rm bash ./share/testing/lib/run.sh ./demo
